services:
  # Backend NestJS
  - type: web
    name: anapath-backend
    runtime: node
    plan: free
    rootDir: back_anapath
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: anapath-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: anapath-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: anapath-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: anapath-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: anapath-db
          property: database
      - key: NOTIFICATION_API_URL
        sync: false
      - key: ANAPATH_ID
        sync: false
      - key: CHU_CMS_SERVICE_URL
        sync: false
      - key: ACCUEIL_BASE_URL
        value: https://acceuil-back-production.up.railway.app
      - key: ANAPATH_SERVICE_ID
        value: 14a94274-db57-49e3-9375-1e642729b92b
      - key: NOTIF_SERVICE_URL
        value: https://prescription-back-7m7a.onrender.com
      - key: CORS_ORIGINS
        sync: false

databases:
  - name: anapath-db
    plan: free
    databaseName: anapath_db
    user: anapath_user